### ISSUE TITLE
哦~我亲爱的浏览器，它无法自动关闭，这使我的心暂息——可那又如何的蒙蔽！

### ISSUE THREAD

**Issue by EillesWan** [LiteyukiStudio/LiteyukiBot#68]
# 问题反馈

## **描述问题**

运行轻雪机器人，发现当 **进行网页渲染** 后关闭轻雪，其打开的浏览器无法自动关闭。\
且每次重启就开一次，如此往复，越开越多。

## **如何复现**

打开轻雪，与其谈话，发送“状态”，开始渲染，截停轻雪，使用控+丙，即可复现。

若不截停，与其谈话，发送如下：“重启轻雪”，复启而后，仍言“状态”，再次渲染，又多一个，浏览进程，非手动则，无法关闭。

### 预期

让轻雪启动的浏览器，自动关闭，才符合我的预期。

### 实际

浏览器是越来越多了，如若无人之境。

## **日志或截图**

忘了截图

## **装置情报**

处理器	超威半导体 锐龙 伍 贰仟伍佰低压 及 镭龙移动显卡\
内存	捌 吉字节\
版本	视窗系统 拾 专业版壹玖〇肆伍点肆陆伍壹\
版号	贰十贰半贰 壹玖〇肆伍点肆陆伍壹\
磐蛇	蟒蛇 叁点拾点拾壹: 柒丁肆丙丙伍甲\
览镜	微软 边缘 壹贰贰点〇点贰叁陆伍点捌〇

## **补充内容**

已试修之，疲矣，且先寐。

**Comment by EillesWan** [comment]
此等壮举，邀诸位共赏

**Comment by snowykami** [comment]
已阅，占用2GB处理

**Comment by sj817** [comment]
秀儿

**Comment by ElapsingDreams** [comment]
已阅，羽言暂搁置处理

**Comment by snowykami** [comment]
已暂时解决

**Comment by snowykami** [comment]
❤️
