### ISSUE TITLE
Resource: 轻雪Kakyo语言包

### ISSUE THREAD

**Issue by snowykami** [LiteyukiStudio/LiteyukiBot#82]
---
name: 轻雪Kakyo语言包 稳定版
desc: Liteyuki Bot的语言包，用于提供多种语言的翻译。
link: https://cdn.liteyuki.icu/static/lrp/kakyo.zip
homepage: https://github.com/Nanaloveyuki/liteyuki-langpack
author: Nanaloveyuki
---
# Resource: 轻雪Kakyo语言包 稳定版
## 发布信息
Liteyuki Bot的语言包，用于提供多种语言的翻译。
**名称**: 轻雪Kakyo语言包 稳定版
**描述**: Liteyuki Bot的语言包，用于提供多种语言的翻译。
**作者**: Nanaloveyuki
**主页**: https://github.com/Nanaloveyuki/liteyuki-langpack
**下载**: https://cdn.liteyuki.icu/static/lrp/kakyo.zip

**Comment by liteyuki-flow** [comment]
已收到资源包发布请求，我会马上开始预检. 如需修改请直接编辑issue，请不要新建issue，我会自动检查

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，等待管理员人工审核
## 元数据
**名称**: 轻雪第三方语言包(Kakyo Ver.)
**描述**: 非轻雪机器人官方的第三方语言包
**版本**: 2024.5.31

**Comment by snowykami** [comment]
审核通过

**Comment by liteyuki-flow** [comment]
✅ 资源包 轻雪Kakyo语言包 稳定版 已发布！商店页面稍后就会更新。
